name: tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  run-tests:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: set up Node for npm
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key:  ${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        if:   steps.cache.outputs.cache-hit != 'true'
        run:  npm ci

      - name: run tests
        run:  npm test
